spring:
  config:
    activate:
      on-profile: test

  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:logback-test.xml




